name: Laravel Deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest

    steps:
      # Setup PHP 8.3
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, curl, xml, tokenizer, sqlite, gd, pdo_mysql
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      # Setup Node.js (latest LTS)
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      # Checkout repository
      - uses: actions/checkout@v3

      # Copy .env if missing (optional, you can push your own .env or use secrets)
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      # Install PHP dependencies
      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --no-scripts

      # Install frontend dependencies & build assets
      - name: Install NPM Dependencies and Build
        run: |
          npm ci
          npm run build

      # SSH deploy commands
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.7.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/curacel-hackings/
            git pull origin main
            rm -rf node_modules
            composer install --prefer-dist --no-dev --optimize-autoloader --no-interaction
            npm ci
            npm run build
            php artisan migrate --force
            php artisan optimize:clear
            sudo supervisorctl restart all
